### ISSUE TITLE
Can't install via composer

### ISSUE THREAD

**Issue by garethworld** [eXpl0it3r/kirby-uniform-recaptcha#2]
Looks like the packages is missing:

`  Could not find a matching version of package expl0it3r/uniform-recaptcha.`

**Comment by eXpl0it3r** [comment]
[The package](https://packagist.org/packages/expl0it3r/kirby-uniform-recaptcha) has the same name as the repository, try adding `expl0it3r/kirby-uniform-recaptcha` instead

Looks like I had it wrong in the read me, will fix it, right now.
Thanks for bringing it to my attention 🙂
